### PR TITLE
use travis homebrew addon for reliability

### PR DESCRIPTION
**Pull request by stephengroat**

### CODE REVIEW

**Comment by dfed** [comment]
Thank you for the contribution @stephengroat! Can you add a link to documentation that explains this change? I don't understand what's going on here as-is.

**Comment by stephengroat** [comment]
sure!

travis has an [`addon` system for installing osx packages](https://docs.travis-ci.com/user/installing-dependencies/#installing-packages-on-macos) that's based on `homebrew-bundle`. by moving to the [travis `brewfile` addon](https://docs.travis-ci.com/user/installing-dependencies/#using-a-brewfile), a specifically tested `ruby` version is used through `rvm` to ensure reliability & speed

**Comment by dfed** [comment]
Awesome! Thanks for the additional details. I don't understand why only one of our CI builds were triggered though. Any chance you can rebase `master` and force push to kick off a new set of builds?

**Comment by stephengroat** [comment]
@dfed the required travis check is forced on branches only. since this is a pr on my branch, it's never going to trigger :-)

**Comment by dfed** [comment]
Ahh shoot. @ljharb when you get a chance, can you help us out? I don't have the permissions to modify our branch requirements, and I'd love to be able to have external contributors help out like this.

**Comment by ljharb** [comment]
fixed :-) PR should be required; branch shouldn't ever be.

**Pull request merged**
