### PR TITLE
[CI] Switch to Circle CI

### PR DESCRIPTION
**Pull request by qyang-nj**
Replace Travis CI with Circle CI.

Issue #102 should be fixed by this.

### CODE REVIEW

**Comment by qyang-nj** [comment]
@dfed still testing. I'll remove Travis CI when everything is working.

**Comment by qyang-nj** [comment]
Fun fact: It took 7 mins for Circle Ci to pass all tests, while Travis CI took 21 mins.

> Circle CI
image

> Travis CI
image

**Comment by bachand** [comment]
Thanks Qing! Looking forward to removing my Xcode 9 hacks on my Siri PR!

**Comment by bachand** [comment]
Cc: @thedavidharris

**Pull request merged**
