### PR TITLE
Improve test structure

### PR DESCRIPTION
**Pull request by dfed**
This PR resolves https://github.com/airbnb/BuckSample/issues/69, and also generally improves how we declare tests.

### CODE REVIEW

**Comment by bachand** [comment]
😍 this is great! Small nit is that it could be cool to add rules for each of them to our `Makefile`. AFAICT it seems like these tests are run in CI though so that’s great.

Thanks @dfed 🙏

**Comment by dfed** [comment]
I was tempted to _remove_ `ui_test` from our Makefile, since all the tests will be run with `make test` at this point. I think these were separated out before because `ui_test` wasn't working, but I'm not sure.

**Comment by bachand** [comment]
> I was tempted to _remove_ `ui_test` from our Makefile

I support this. What I mostly find confusing is that we have a rule for one type of test and not the others.

**Comment by dfed** [comment]
And here's the PR: https://github.com/airbnb/BuckSample/pull/72

**Pull request merged**
